import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # For enhanced plotting

# --- Configuration ---
script_dir = os.path.dirname(os.path.abspath(__file__))
# The input CSV file generated by the 'annual_energy_cost_compiler' Canvas
input_csv_path = os.path.join(script_dir, "output", "scenario_net_costs.csv")

# Output CSV file for breakeven results
output_breakeven_csv_path = os.path.join(script_dir, "output", "breakeven_periods.csv")

# Output directory for plots
plots_output_directory = os.path.join(script_dir, "output", "breakeven_plots")
os.makedirs(plots_output_directory, exist_ok=True)


print("--- Starting Breakeven Period Calculation ---")

if not os.path.exists(input_csv_path):
    print(f"Error: Input CSV file not found at {input_csv_path}.")
    print("Please ensure the 'annual_energy_cost_compiler' script has been run successfully to generate this file.")
    exit()

try:
    # Load the compiled data from the CSV
    compiled_df = pd.read_csv(input_csv_path)

    # Convert all relevant columns to numeric, handling potential formatting from previous script
    for col in compiled_df.columns:
        if col != 'Month':
            compiled_df[col] = pd.to_numeric(compiled_df[col], errors='coerce')

    # Extract the 'Total' (annual net costs) row
    annual_net_costs_row = compiled_df[compiled_df['Month'] == 'Total'].iloc[0]
    
    # Extract the 'Installation Cost' row
    installation_costs_row = compiled_df[compiled_df['Month'] == 'Installation Cost'].iloc[0]

    # Get the annual net cost for the 'NoBattery' scenario (baseline)
    no_battery_annual_cost = annual_net_costs_row['NoBattery']
    
    # List to store breakeven results
    breakeven_results = []

    print(f"\nBaseline Annual Net Cost (No Battery): {no_battery_annual_cost:.2f} EUR")

    # Iterate through battery scenarios (excluding 'NoBattery' itself)
    for scenario_name in compiled_df.columns:
        if scenario_name == 'Month' or scenario_name == 'NoBattery':
            continue

        battery_annual_cost = annual_net_costs_row[scenario_name]
        battery_installation_cost = installation_costs_row[scenario_name]

        print(f"\n--- Scenario: {scenario_name} ---")
        print(f"  Battery Annual Net Cost: {battery_annual_cost:.2f} EUR")
        print(f"  Battery Installation Cost: {battery_installation_cost:.2f} EUR")

        # Calculate Annual Savings (Returns Per Year)
        # Savings are the reduction in annual net cost compared to the 'NoBattery' scenario
        annual_savings = no_battery_annual_cost - battery_annual_cost
        
        # Initialize breakeven_period_with_setup
        breakeven_period_with_setup = np.nan

        if annual_savings <= 0:
            print(f"  Warning: No annual savings for {scenario_name} (Annual Savings: {annual_savings:.2f} EUR). Breakeven cannot be calculated.")
        else:
            print(f"  Annual Savings (Returns Per Year): {annual_savings:.2f} EUR/year")

            # Breakeven Period With Considering Setup Cost
            if battery_installation_cost > 0:
                breakeven_period_with_setup = battery_installation_cost / annual_savings
                print(f"  Breakeven Period (With Setup Cost): {breakeven_period_with_setup:.2f} years")
            else:
                breakeven_period_with_setup = 0.0 # Or np.nan, depending on desired representation
                print(f"  Breakeven Period (With Setup Cost): 0.00 years (No installation cost)")


        breakeven_results.append({
            'Scenario': scenario_name,
            'Battery_Size_kWh': annual_net_costs_row.name if 'Total' == annual_net_costs_row.name else annual_net_costs_row.index[annual_net_costs_row == battery_annual_cost].tolist()[0] if 'Total' != annual_net_costs_row.name else annual_net_costs_row.name, # This part might need adjustment based on exact df structure
            'Annual_Net_Cost_EUR': battery_annual_cost,
            'Installation_Cost_EUR': battery_installation_cost,
            'Returns_Per_Year_EUR': annual_savings, # Changed column name here
            'Breakeven_With_Setup_Years': f"{breakeven_period_with_setup:.2f}" if pd.notna(breakeven_period_with_setup) else str(breakeven_period_with_setup)
        })

    # Convert the list of results to a DataFrame for CSV export
    results_df = pd.DataFrame(breakeven_results)
    
    # Re-order columns for better readability if desired
    desired_columns = [
        'Scenario', 'Battery_Size_kWh', 'Annual_Net_Cost_EUR', 'Installation_Cost_EUR', 
        'Returns_Per_Year_EUR', 'Breakeven_With_Setup_Years' # Changed column name here
    ]
    
    # Infer Battery_Size_kWh from scenario name and sort
    results_df['Battery_Size_Num'] = results_df['Scenario'].apply(lambda x: int(x.replace('kWh', '')) if 'kWh' in x else 0)
    results_df = results_df.sort_values(by='Battery_Size_Num').reset_index(drop=True)
    results_df['Battery_Size_kWh'] = results_df['Battery_Size_Num'].apply(lambda x: f"{int(x)} kWh" if x > 0 else "No Battery")
    results_df = results_df.drop(columns=['Battery_Size_Num']) # Drop the temporary numeric column

    results_df = results_df[desired_columns]


    results_df.to_csv(output_breakeven_csv_path, index=False, float_format='%.2f')
    print(f"\n--- Breakeven periods saved to: {output_breakeven_csv_path} ---")
    print("\nBreakeven Results Overview:")
    print(results_df)

    # --- Plotting Bar Graphs ---
    print("\n--- Generating Breakeven Plots ---")

    # Ensure numeric types for plotting
    plot_df = results_df.copy()
    plot_df['Returns_Per_Year_EUR'] = pd.to_numeric(plot_df['Returns_Per_Year_EUR'], errors='coerce')
    plot_df['Breakeven_With_Setup_Years'] = pd.to_numeric(plot_df['Breakeven_With_Setup_Years'], errors='coerce')

    # Sort the plotting DataFrame by numeric battery size for correct x-axis order
    plot_df['Battery_Size_Sort'] = plot_df['Scenario'].apply(lambda x: int(x.replace('kWh', '')) if 'kWh' in x else 0)
    plot_df = plot_df.sort_values(by='Battery_Size_Sort').reset_index(drop=True)


    # 1. Bar Graph for Returns_Per_Year_EUR
    fig1, ax1 = plt.subplots(figsize=(12, 7))
    sns.barplot(x='Battery_Size_kWh', y='Returns_Per_Year_EUR', data=plot_df, palette='viridis', ax=ax1)
    ax1.set_title('Annual Returns Per Battery Scenario (Savings vs. No Battery)')
    ax1.set_xlabel('Battery Nominal Capacity')
    ax1.set_ylabel('Returns Per Year (EUR)')
    ax1.grid(axis='y', linestyle='--', alpha=0.7)
    
    # Add value labels on top of bars
    for p in ax1.patches:
        ax1.annotate(f"{p.get_height():.2f}", 
                     (p.get_x() + p.get_width() / 2., p.get_height()), 
                     ha='center', va='center', fontsize=9, color='black', xytext=(0, 5), 
                     textcoords='offset points')

    returns_plot_path = os.path.join(plots_output_directory, "Annual_Returns_Per_Battery_Scenario.png")
    fig1.savefig(returns_plot_path, dpi=300)
    plt.close(fig1)
    print(f"Bar graph for Annual Returns saved to: {returns_plot_path}")


    # 2. Bar Graph for Breakeven_With_Setup_Years
    fig2, ax2 = plt.subplots(figsize=(12, 7))
    sns.barplot(x='Battery_Size_kWh', y='Breakeven_With_Setup_Years', data=plot_df, palette='magma', ax=ax2)
    ax2.set_title('Breakeven Period Per Battery Scenario (Considering Setup Cost)')
    ax2.set_xlabel('Battery Nominal Capacity')
    ax2.set_ylabel('Breakeven Period (Years)')
    ax2.grid(axis='y', linestyle='--', alpha=0.7)

    # Add value labels on top of bars
    for p in ax2.patches:
        if pd.notna(p.get_height()): # Only annotate if not NaN
            ax2.annotate(f"{p.get_height():.2f}", 
                         (p.get_x() + p.get_width() / 2., p.get_height()), 
                         ha='center', va='center', fontsize=9, color='black', xytext=(0, 5), 
                         textcoords='offset points')
    
    breakeven_plot_path = os.path.join(plots_output_directory, "Breakeven_Period_Per_Battery_Scenario.png")
    fig2.savefig(breakeven_plot_path, dpi=300)
    plt.close(fig2)
    print(f"Bar graph for Breakeven Period saved to: {breakeven_plot_path}")


except Exception as e:
    print(f"An error occurred during breakeven calculation or plotting: {e}")
    import traceback
    traceback.print_exc()

print("\nBreakeven period calculation and plotting completed.")
