import pandas as pd
import os
import matplotlib.pyplot as plt
import zipfile

# Define the directory where the CSV outputs are saved
script_dir = os.path.dirname(os.path.abspath(__file__))
output_dir = os.path.join(script_dir, "output")
plots_zip_dir = os.path.join(output_dir, "plots_archive") # New directory for plots before zipping
os.makedirs(plots_zip_dir, exist_ok=True) # Ensure this directory exists

# Define the paths to the generated CSV files for ALL scenarios
scenario_csv_paths = {
    "battery_5k": {
        "display_name": "Battery (5kWh)",
        "monthly": os.path.join(output_dir, "monthly_energy_summary_2023_battery_5k_kWh.csv"),
        "yearly": os.path.join(output_dir, "yearly_energy_summary_2023_battery_5k_kWh.csv")
    },
    "nobattery": {
        "display_name": "No Battery",
        "monthly": os.path.join(output_dir, "monthly_energy_summary_2023_nobattery_kWh.csv"),
        "yearly": os.path.join(output_dir, "yearly_energy_summary_2023_nobattery_kWh.csv")
    },
    "battery_8k": {
        "display_name": "Battery (8kWh)",
        "monthly": os.path.join(output_dir, "monthly_energy_summary_2023_battery_8k_kWh.csv"),
        "yearly": os.path.join(output_dir, "yearly_energy_summary_2023_battery_8k_kWh.csv")
    },
    "battery_12k": {
        "display_name": "Battery (12kWh)",
        "monthly": os.path.join(output_dir, "monthly_energy_summary_2023_battery_12k_kWh.csv"),
        "yearly": os.path.join(output_dir, "yearly_energy_summary_2023_battery_12k_kWh.csv")
    },
    "battery_15k": {
        "display_name": "Battery (15kWh)",
        "monthly": os.path.join(output_dir, "monthly_energy_summary_2023_battery_15k_kWh.csv"),
        "yearly": os.path.join(output_dir, "yearly_energy_summary_2023_battery_15k_kWh.csv")
    },
    "battery_20k": {
        "display_name": "Battery (20kWh)",
        "monthly": os.path.join(output_dir, "monthly_energy_summary_2023_battery_20k_kWh.csv"),
        "yearly": os.path.join(output_dir, "yearly_energy_summary_2023_battery_20k_kWh.csv")
    },
    "battery_26k": {
        "display_name": "Battery (26kWh)",
        "monthly": os.path.join(output_dir, "monthly_energy_summary_2023_battery_26k_kWh.csv"),
        "yearly": os.path.join(output_dir, "yearly_energy_summary_2023_battery_26k_kWh.csv")
    }
}

print("--- Starting Energy Data Analysis from CSVs ---")

# --- 1. Load the CSV files ---
df_monthly = {}
df_yearly = {}
loaded_scenarios = []

for identifier, paths in scenario_csv_paths.items():
    try:
        df_monthly[identifier] = pd.read_csv(paths["monthly"], index_col="Month")
        df_yearly[identifier] = pd.read_csv(paths["yearly"], index_col="Metric")
        loaded_scenarios.append(identifier)
        print(f"Successfully loaded data for {paths['display_name']}.")
    except FileNotFoundError as e:
        print(f"\nError: CSV file not found for {paths['display_name']}.")
        print(f"Missing file: {e.filename}")
        print(f"Skipping {paths['display_name']} scenario. Please ensure it is generated by the previous script.")

if not loaded_scenarios:
    print("\nNo scenario data could be loaded. Exiting.")
    exit()

# --- 2. Display Monthly Summaries Side-by-Side (Optional, can be very verbose for many scenarios) ---
print("\n" + "="*80)
print("             MONTHLY ENERGY FLOW COMPARISON (kWh)             ")
print("="*80 + "\n")

for identifier in loaded_scenarios:
    display_name = scenario_csv_paths[identifier]["display_name"]
    if identifier in df_monthly:
        print(f"\n--- {display_name} Scenario Monthly Summary ---")
        print(df_monthly[identifier].to_string(float_format="%.2f"))

# --- 3. Key Metric Comparison (Yearly Totals) ---
print("\n" + "="*80)
print("             YEARLY TOTALS COMPARISON (kWh)             ")
print("="*80 + "\n")

# Combine yearly data for easier comparison across all loaded scenarios
yearly_comparison = pd.DataFrame()
for identifier in loaded_scenarios:
    display_name = scenario_csv_paths[identifier]["display_name"]
    if identifier in df_yearly:
        yearly_comparison[display_name] = df_yearly[identifier]['Value']

print(yearly_comparison.to_string(float_format="%.2f"))

# --- 4. Analyze the Impact of the Battery (if 'No Battery' scenario is present) ---
print("\n" + "="*80)
print("             BATTERY IMPACT ANALYSIS             ")
print("="*80 + "\n")

if "nobattery" in loaded_scenarios:
    total_demand = yearly_comparison.loc["Total Period Demand (kWh)", "No Battery"]
    pv_production = yearly_comparison.loc["Total Period PV Production (kWh)", "No Battery"]

    print(f"Total Annual Demand: {total_demand:.2f} kWh (Consistent across scenarios with same demand profile)")
    print(f"Total Annual PV Production: {pv_production:.2f} kWh (Consistent across scenarios with same PV profile)")
    print("-" * 60)

    # Filter out the 'nobattery' scenario from comparison
    battery_scenarios_for_analysis = [s for s in loaded_scenarios if s != "nobattery"]

    for identifier in battery_scenarios_for_analysis:
        scenario_label = scenario_csv_paths[identifier]["display_name"]
        print(f"\n--- Comparing {scenario_label} vs. No Battery ---")

        grid_import_current = yearly_comparison.loc["Total Period Grid Import (kWh)", scenario_label]
        grid_import_nobattery = yearly_comparison.loc["Total Period Grid Import (kWh)", "No Battery"]
        grid_export_current = yearly_comparison.loc["Total Period Grid Export (kWh)", scenario_label]
        grid_export_nobattery = yearly_comparison.loc["Total Period Grid Export (kWh)", "No Battery"]
        pv_self_consumption_current = yearly_comparison.loc["Total Period PV Self-Consumption (kWh)", scenario_label]
        pv_self_consumption_nobattery = yearly_comparison.loc["Total Period PV Self-Consumption (kWh)", "No Battery"]
        self_sufficiency_current = yearly_comparison.loc["Total Period Self-Sufficiency (kWh)", scenario_label]
        self_sufficiency_nobattery = yearly_comparison.loc["Total Period Self-Sufficiency (kWh)", "No Battery"]

        battery_charge_current = yearly_comparison.loc["Total Period Battery Charge (kWh)", scenario_label] if "Total Period Battery Charge (kWh)" in yearly_comparison.index else 0.0
        battery_discharge_current = yearly_comparison.loc["Total Period Battery Discharge (kWh)", scenario_label] if "Total Period Battery Discharge (kWh)" in yearly_comparison.index else 0.0


        print(f"   Grid Import ({scenario_label}):         {grid_import_current:.2f} kWh")
        print(f"   Grid Import (No Battery):    {grid_import_nobattery:.2f} kWh")
        print(f"   Reduction in Grid Import:    {grid_import_nobattery - grid_import_current:.2f} kWh")
        print("-" * 40)

        print(f"   Grid Export ({scenario_label}):         {grid_export_current:.2f} kWh")
        print(f"   Grid Export (No Battery):    {grid_export_nobattery:.2f} kWh")
        print(f"   Reduction in Grid Export:    {grid_export_nobattery - grid_export_current:.2f} kWh")
        print("-" * 40)

        print(f"   PV Self-Consumption ({scenario_label}):      {pv_self_consumption_current:.2f} kWh")
        print(f"   PV Self-Consumption (No Battery): {pv_self_consumption_nobattery:.2f} kWh")
        print(f"   Increase in Self-Consumption: {pv_self_consumption_current - pv_self_consumption_nobattery:.2f} kWh")
        print("-" * 40)

        print(f"   Self-Sufficiency ({scenario_label}):      {self_sufficiency_current:.2f} kWh")
        print(f"   Self-Sufficiency (No Battery): {self_sufficiency_nobattery:.2f} kWh")
        print(f"   Increase in Self-Sufficiency: {self_sufficiency_current - self_sufficiency_nobattery:.2f} kWh")
        print("-" * 40)

        print(f"   Total Battery Charge ({scenario_label}): {battery_charge_current:.2f} kWh")
        print(f"   Total Battery Discharge ({scenario_label}): {battery_discharge_current:.2f} kWh")
        print("-" * 60)
else:
    print("\n'No Battery' scenario not loaded. Skipping battery impact analysis.")

# --- 5. Visualization (using Matplotlib, individual plots for monthly data) ---
print("\nGenerating individual plots for monthly metrics across all scenarios...")

# List of metrics to plot individually
plot_metrics = [
    "Demand (kWh)", "PV Production (kWh)", "Grid Import (kWh)", "Grid Export (kWh)",
    "PV Self-Consumption (kWh)", "Self-Sufficiency (kWh)"
]

generated_plot_files = [] # To store names of all generated plot files for zipping

# Define colors, linestyles, and markers for each scenario for consistency
# Extended to include new scenarios
plot_styles = {
    'Battery (5kWh)': {'color': 'blue', 'linestyle': '-', 'marker': 'o'},
    'No Battery': {'color': 'red', 'linestyle': '--', 'marker': 'x'},
    'Battery (8kWh)': {'color': 'green', 'linestyle': '-.', 'marker': '^'},
    'Battery (12kWh)': {'color': 'purple', 'linestyle': ':', 'marker': 's'},
    'Battery (15kWh)': {'color': 'orange', 'linestyle': (0, (3, 1, 1, 1)), 'marker': 'D'}, # Dash-dot-dot
    'Battery (20kWh)': {'color': 'brown', 'linestyle': (0, (5, 1)), 'marker': 'p'}, # Densely dashed
    'Battery (26kWh)': {'color': 'cyan', 'linestyle': (0, (3, 5, 1, 5)), 'marker': '*'} # Loosely dash-dotted
}


# --- Plotting function for monthly data (modified to iterate through all loaded scenarios) ---
def plot_monthly_metric(metric, monthly_dataframes, plot_dir, scenario_styles):
    fig, ax = plt.subplots(figsize=(10, 10 * 13 / 21)) # Maintain 21:13 ratio

    plotted_any = False
    for identifier in loaded_scenarios:
        display_name = scenario_csv_paths[identifier]["display_name"]
        if identifier in monthly_dataframes and metric in monthly_dataframes[identifier].columns:
            ax.plot(monthly_dataframes[identifier].index, monthly_dataframes[identifier][metric],
                    label=display_name,
                    marker=scenario_styles.get(display_name, {}).get('marker', 'o'),
                    linestyle=scenario_styles.get(display_name, {}).get('linestyle', '-'),
                    color=scenario_styles.get(display_name, {}).get('color', 'black'),
                    drawstyle='steps-post')
            plotted_any = True
        else:
            print(f"    Skipping plotting '{metric}' for {display_name}: Data column not found.")


    if not plotted_any:
        print(f"Skipping plot for '{metric}': No data available across any of the loaded scenarios.")
        plt.close(fig)
        return None

    ax.set_ylabel(metric)
    ax.set_xlabel("Month")
    ax.set_title(f'Monthly {metric} Comparison Across Scenarios', fontsize=14)
    ax.legend(loc='best') # Legend inside the plot, matplotlib determines best location
    ax.grid(True, linestyle='--', alpha=0.7)
    plt.xticks(rotation=45, ha='right')

    filename = f"monthly_{metric.replace(' (kWh)', '').replace(' (%)', '').replace(' ', '_').lower()}_comparison.png"
    filepath = os.path.join(plot_dir, filename)
    plt.tight_layout()
    plt.savefig(filepath)
    plt.close(fig)
    return filepath

for metric in plot_metrics:
    filepath = plot_monthly_metric(metric, df_monthly, plots_zip_dir, plot_styles)
    if filepath:
        generated_plot_files.append(filepath)
        print(f"Saved: {filepath}")

# Bar chart for yearly totals comparison (key metrics) - remains a bar chart
# Ensure all relevant metrics are included, especially battery charge/discharge if present
yearly_plot_metrics_order = [
    "Total Period Demand (kWh)",
    "Total Period PV Production (kWh)",
    "Total Period Grid Import (kWh)",
    "Total Period Grid Export (kWh)",
    "Total Period PV Self-Consumption (kWh)",
    "Total Period Self-Sufficiency (kWh)",
    "Overall Self-Consumption Rate (%)",
    "Overall Self-Sufficiency Rate (%)"
]

# Dynamically add battery metrics if they exist in the combined yearly_comparison DataFrame
if "Total Period Battery Charge (kWh)" in yearly_comparison.index:
    yearly_plot_metrics_order.append("Total Period Battery Charge (kWh)")
if "Total Period Battery Discharge (kWh)" in yearly_comparison.index:
    yearly_plot_metrics_order.append("Total Period Battery Discharge (kWh)")

# Filter bar_chart_data to only include metrics that are actually present
present_yearly_metrics = [m for m in yearly_plot_metrics_order if m in yearly_comparison.index]
bar_chart_data = yearly_comparison.loc[present_yearly_metrics]

fig2, ax2 = plt.subplots(figsize=(12, 12 * 13 / 21)) # Maintain 21:13 ratio
bar_chart_data.plot(kind='bar', ax=ax2, width=0.7)
ax2.set_title('Yearly Energy Totals Comparison Across All Scenarios', fontsize=16)
ax2.set_ylabel('Value (kWh or %)')
ax2.set_xlabel('Metric')
ax2.set_xticklabels([label.replace(' (kWh)', '').replace(' (%)', '') for label in bar_chart_data.index], rotation=45, ha='right')
ax2.yaxis.grid(True, linestyle='--', alpha=0.7)
ax2.legend(title="Scenario", loc='best')
plt.tight_layout()
yearly_bar_filepath = os.path.join(plots_zip_dir, 'yearly_energy_comparison_bar_all_scenarios.png')
plt.savefig(yearly_bar_filepath)
generated_plot_files.append(yearly_bar_filepath)
print(f"Saved: {yearly_bar_filepath}")
plt.close(fig2)


# --- Create a zip file of all generated plots ---
zip_filename = os.path.join(output_dir, "energy_plots_2023_kWh_all_scenarios.zip")
print(f"\nCreating zip archive: {zip_filename}")

with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for plot_file in generated_plot_files:
        zipf.write(plot_file, os.path.basename(plot_file))
        print(f"   Added {os.path.basename(plot_file)} to zip.")

print(f"All plots successfully zipped to: {zip_filename}")

# Clean up the temporary plots directory
try:
    os.rmdir(plots_zip_dir)
    print(f"Temporary plots directory removed: {plots_zip_dir}")
except OSError as e:
    print(f"Error removing temporary plots directory {plots_zip_dir}: {e}")


print("\n--- Energy Data Analysis Complete ---")
print("Check the 'output' folder for CSV summaries and the .zip file containing plots.")